export const VAULT_ADDRESS = '0x26F9Ec14564B73DC95a79898bce62656a9A5503D' as const;

export const VAULT_ABI = [
  // ─── Read Functions ───────────────────────────────────────────────────
  {
    name: 'getPortfolioSummary',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'ethValueUsd', type: 'uint256' },
      { name: 'usdcValueUsd', type: 'uint256' },
      { name: 'totalUsd', type: 'uint256' },
      { name: 'currentDrift', type: 'int256' },
      { name: 'targetBps', type: 'uint256' },
      { name: 'rebalanceCount', type: 'uint256' },
      { name: 'totalShares', type: 'uint256' },
      { name: 'paused', type: 'bool' },
    ],
  },
  {
    name: 'getSharePrice',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    name: 'getUserPosition',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [
      { name: 'shares', type: 'uint256' },
      { name: 'ethValue', type: 'uint256' },
      { name: 'usdcValue', type: 'uint256' },
    ],
  },
  {
    name: 'getRebalanceStats',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'rebalanceCount', type: 'uint256' },
      { name: 'lastRebalanceBlock', type: 'uint256' },
      { name: 'lastRebalancePrice', type: 'uint256' },
      { name: 'totalVolumeSwapped', type: 'uint256' },
      { name: 'totalGasUsed', type: 'uint256' },
      { name: 'totalSlippageLost', type: 'uint256' },
    ],
  },
  {
    name: 'getVaultConfig',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'targetAllocationBps', type: 'uint256' },
      { name: 'driftThresholdBps', type: 'uint256' },
      { name: 'maxSlippageBps', type: 'uint256' },
      { name: 'minRebalanceInterval', type: 'uint256' },
      { name: 'activeStrategy', type: 'address' },
      { name: 'swapAdapter', type: 'address' },
      { name: 'yieldAdapter', type: 'address' },
      { name: 'priceFeed', type: 'address' },
    ],
  },
  {
    name: 'getFeeInfo',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'managementFeeBps', type: 'uint256' },
      { name: 'performanceFeeBps', type: 'uint256' },
      { name: 'highWaterMark', type: 'uint256' },
      { name: 'accruedFees', type: 'uint256' },
      { name: 'feeRecipient', type: 'address' },
    ],
  },
  {
    name: 'getGuardStatus',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'circuitBreakerTripped', type: 'bool' },
      { name: 'maxPriceChangeBps', type: 'uint256' },
      { name: 'lastKnownPrice', type: 'uint256' },
      { name: 'rebalancesInWindow', type: 'uint256' },
      { name: 'maxRebalancesPerWindow', type: 'uint256' },
      { name: 'maxSwapSizeBps', type: 'uint256' },
    ],
  },
  {
    name: 'getYieldInfo',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'totalDepositedToAave', type: 'uint256' },
      { name: 'totalYieldEarned', type: 'uint256' },
      { name: 'yieldEnabled', type: 'bool' },
    ],
  },
  {
    name: 'checkUpkeep',
    type: 'function',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'bytes' }],
    outputs: [
      { name: 'upkeepNeeded', type: 'bool' },
      { name: 'performData', type: 'bytes' },
    ],
  },
  {
    name: 'getEthPrice',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: 'price', type: 'uint256' },
      { name: 'decimals', type: 'uint8' },
    ],
  },
  {
    name: 'getCurrentDrift',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'int256' }],
  },
  {
    name: 'getActiveStrategy',
    type: 'function',
    stateMutability: 'view',
    inputs: [],
    outputs: [
      { name: '', type: 'address' },
      { name: '', type: 'string' },
    ],
  },
  // ─── Write Functions ──────────────────────────────────────────────────
  {
    name: 'deposit',
    type: 'function',
    stateMutability: 'payable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'depositUSDC',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'amount', type: 'uint256' }],
    outputs: [],
  },
  {
    name: 'withdraw',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'shareAmount', type: 'uint256' }],
    outputs: [],
  },
  {
    name: 'emergencyWithdraw',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'performUpkeep',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: '', type: 'bytes' }],
    outputs: [],
  },
  {
    name: 'depositToYield',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'amount', type: 'uint256' }],
    outputs: [],
  },
  {
    name: 'withdrawFromYield',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'amount', type: 'uint256' }],
    outputs: [],
  },
  {
    name: 'harvestYield',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    name: 'setYieldEnabled',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'enabled', type: 'bool' }],
    outputs: [],
  },
  {
    name: 'setActiveStrategy',
    type: 'function',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'strategy', type: 'address' }],
    outputs: [],
  },
  // ─── Events ───────────────────────────────────────────────────────────
  {
    name: 'Deposited',
    type: 'event',
    anonymous: false,
    inputs: [
      { indexed: true, name: 'user', type: 'address' },
      { indexed: false, name: 'ethAmount', type: 'uint256' },
      { indexed: false, name: 'usdcAmount', type: 'uint256' },
      { indexed: false, name: 'sharesIssued', type: 'uint256' },
    ],
  },
  {
    name: 'Withdrawn',
    type: 'event',
    anonymous: false,
    inputs: [
      { indexed: true, name: 'user', type: 'address' },
      { indexed: false, name: 'ethAmount', type: 'uint256' },
      { indexed: false, name: 'usdcAmount', type: 'uint256' },
      { indexed: false, name: 'sharesBurned', type: 'uint256' },
    ],
  },
  {
    name: 'Rebalanced',
    type: 'event',
    anonymous: false,
    inputs: [
      { indexed: true, name: 'blockNumber', type: 'uint256' },
      { indexed: false, name: 'soldEth', type: 'bool' },
      { indexed: false, name: 'swapAmount', type: 'uint256' },
      { indexed: false, name: 'amountOut', type: 'uint256' },
      { indexed: false, name: 'driftBefore', type: 'int256' },
      { indexed: false, name: 'driftAfter', type: 'int256' },
    ],
  },
  {
    name: 'CircuitBreakerTripped',
    type: 'event',
    anonymous: false,
    inputs: [
      { indexed: false, name: 'blockNumber', type: 'uint256' },
      { indexed: false, name: 'reason', type: 'string' },
    ],
  },
] as const;
